<?xml version="1.0" encoding="utf-8"?><Database Name="project" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-C2L51Q9;Initial Catalog=project;Integrated Security=True" SettingsObjectName="WindowsFormsApp14DBproject.Properties.Settings" SettingsPropertyName="projectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Branch" Member="Branches">
    <Type Name="Branch">
      <Column Name="branchID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Branch_Description" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Street_Address" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Postal_Code" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cars" Member="Cars">
    <Type Name="Car">
      <Column Name="carID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="locID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rented" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="color" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="licensePlate" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="make" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="typeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="branchID" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="customerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="goldMember" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="noRentals" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="transID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="beginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="endDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="rentalPeriod" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="carID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="branchID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cusomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="employeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Type" Member="Types">
    <Type Name="Type">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Doors" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dRate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="wRate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mRate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>